name: Daily Commit

on:
  schedule:
    - cron: '30 2 * * *'  # Runs daily at 02:30 UTC

  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # ✅ This allows the workflow to push changes

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # ✅ Prevents conflicts with default token

      - name: Update File - 23f1001611@ds.study.iitm.ac.in
        run: |
          echo "Last run: $(date)" > last_run.txt

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "23f1001611@ds.study.iitm.ac.in"

      - name: Commit and Push Changes
        run: |
          git add last_run.txt
          git commit -m "Automated daily commit - $(date)" || echo "No changes to commit"
          git branch -M main
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
