name: Daily Commit

on:
  schedule:
    # Runs every day at 02:30 UTC
    - cron: '30 2 * * *'

  workflow_dispatch:  # Allows manual triggering

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update File - 23f1001611@ds.study.iitm.ac.in
        run: |
          echo "Last run: $(date)" > last_run.txt

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "23f1001611@ds.study.iitm.ac.in"

      - name: Commit and Push Changes
        run: |
          git add last_run.txt
          git commit -m "Automated daily commit - $(date)" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
